// 檔案路徑: src/app/features/ebook/book-list/books.data.ts
export const BOOKS_DATA = [
    {
        ebookId: 301,
        ebookName: "原子習慣",
        author: "詹姆斯‧克利爾",
        primaryCoverPath: "/assets/images/ebooks/atomic-habits.jpg",
        fixedPrice: 330,
        actualPrice: 250,
        bookDescription: "這是一本從假資料來的、關於原子習慣的詳細描述...",
        categoryName: "心理勵志",
        labels: ["自我成長", "習慣", "暢銷"],
        categoryId: 24,
        isReadable: true // [新增]

    },
    {
        ebookId: 302,
        ebookName: "被討厭的勇氣",
        author: "岸見一郎, 古賀史健",
        primaryCoverPath: "/assets/images/ebooks/courage.jpg",
        fixedPrice: 300,
        actualPrice: 300,
        categoryName: "心理勵志",
        labels: ["阿德勒", "哲學", "人際關係"],
        categoryId: 32,
        isReadable: true // [新增]
    },
    {
        ebookId: 303,
        ebookName: "晶片戰爭",
        author: "克里斯・米勒",
        primaryCoverPath: "/assets/images/ebooks/chip-war.jpg",
        fixedPrice: 550,
        actualPrice: 499,
        categoryName: "商業理財",
        labels: ["科技", "半導體", "國際情勢"],
        categoryId: 33,
        isReadable: true // [新增]
    },
    {
        ebookId: 304,
        ebookName: "沙丘",
        author: "法蘭克・赫伯特",
        primaryCoverPath: "/assets/images/ebooks/dune.jpg",
        fixedPrice: 400,
        actualPrice: null,
        categoryName: "文學小說",
        labels: ["科幻", "史詩", "經典"],
        categoryId: 3,
        isReadable: true // [新增]
    },
    {
        ebookId: 305,
        ebookName: "流浪的地球",
        author: "劉慈欣",
        primaryCoverPath: "/assets/images/ebooks/wandering-earth.jpg",
        fixedPrice: 320,
        actualPrice: 320,
        categoryName: "文學小說",
        labels: ["科幻", "三體", "末日"],
        categoryId: 3,
        isReadable: true // [新增]
    },
    {
        ebookId: 306,
        ebookName: "台北人",
        author: "白先勇",
        primaryCoverPath: "/assets/images/ebooks/taipei-people.jpg",
        fixedPrice: 250,
        actualPrice: 199,
        categoryName: "文學小說",
        labels: ["現代文學", "經典", "台灣"],
        categoryId: 24,
        isReadable: true // [新增]
    },
    {
        ebookId: 307,
        ebookName: "做工的人",
        author: "林立青",
        primaryCoverPath: "/assets/images/ebooks/workers.jpg",
        fixedPrice: 280,
        actualPrice: 280,
        categoryName: "社會科學",
        labels: ["台灣", "社會", "紀實"],
        categoryId: 24,
        isReadable: true // [新增]
    },
    {
        ebookId: 308,
        ebookName: "解憂雜貨店",
        author: "東野圭吾",
        primaryCoverPath: "/assets/images/ebooks/namiya.jpg",
        fixedPrice: 350,
        actualPrice: 280,
        categoryName: "文學小說",
        labels: ["推理", "溫馨", "暢銷"],
        categoryId: 1,
        isReadable: true // [新增]
    },
    {
        ebookId: 309,
        ebookName: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        primaryCoverPath: "/assets/images/ebooks/gatsby.jpg",
        fixedPrice: 450,
        actualPrice: 450,
        categoryName: "歐美文學",
        labels: ["經典", "爵士時代", "小說"],
        categoryId: 7,
        isReadable: true // [新增]
    },
    {
        ebookId: 310,
        ebookName: "To Kill a Mockingbird",
        author: "Harper Lee",
        primaryCoverPath: "/assets/images/ebooks/mockingbird.jpg",
        fixedPrice: 480,
        actualPrice: 399,
        categoryName: "歐美文學",
        labels: ["經典", "法律", "小說"],
        categoryId: 1,
        isReadable: true // [新增]
    },
    {
        ebookId: 311,
        ebookName: "Nineteen Eighty-Four",
        author: "George Orwell",
        primaryCoverPath: "/assets/images/ebooks/1984.jpg",
        fixedPrice: 360,
        actualPrice: 360,
        categoryName: "歐美文學",
        labels: ["反烏托邦", "經典", "科幻"],
        categoryId: 8,
        isReadable: true // [新增]
    },
    {
        ebookId: 312,
        ebookName: "Pride and Prejudice",
        author: "Jane Austen",
        primaryCoverPath: "/assets/images/ebooks/pride.jpg",
        fixedPrice: 420,
        actualPrice: null,
        categoryName: "歐美文學",
        labels: ["愛情", "經典", "小說"],
        categoryId: 1,
        isReadable: true // [新增]
    },
    {
        ebookId: 313,
        ebookName: "Moby-Dick",
        author: "Herman Melville",
        primaryCoverPath: "/assets/images/ebooks/moby-dick.jpg",
        fixedPrice: 500,
        actualPrice: 500,
        categoryName: "歐美文學",
        labels: ["冒險", "經典", "海洋"],
        categoryId: 1,
        isReadable: true // [新增]
    },
    {
        ebookId: 314,
        ebookName: "Frankenstein",
        author: "Mary Shelley",
        primaryCoverPath: "/assets/images/ebooks/frankenstein.jpg",
        fixedPrice: 380,
        actualPrice: 320,
        categoryName: "歐美文學",
        labels: ["哥德", "科幻", "恐怖"],
        categoryId: 24,
        isReadable: true // [新增]
    },
    {
        ebookId: 315,
        ebookName: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        primaryCoverPath: "/assets/images/ebooks/lotr.gif",
        fixedPrice: 990,
        actualPrice: 799,
        categoryName: "奇幻文學",
        labels: ["史詩", "奇幻", "經典"],
        categoryId: 7,
        isReadable: true // [新增]
    },
    {
        ebookId: 316,
        ebookName: "The Adventures of Sherlock Holmes",
        author: "Arthur Conan Doyle",
        primaryCoverPath: "/assets/images/ebooks/sherlock.jpg",
        fixedPrice: 450,
        actualPrice: 450,
        categoryName: "歐美文學",
        labels: ["推理", "經典", "偵探"],
        categoryId: 24,
        isReadable: true // [新增]
    }
];
